name: Deploy To Lambda

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy_dev:
    name: Deploy to lambda
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm i

      - name: Bundle app
        run: npm run build

      - name: Zip bundle
        run: cd dist && zip -r bundle.zip index.js*

      - name: Deploy zip file to lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: csv_repo_upload
          zip_file: dist/bundle.zip
